### ISSUE TITLE
GH Action for DEV Integration is failing for "Check for New Comments for a DEV User"

### ISSUE THREAD

**Issue by KRRISH96** [orbit-love/github-actions-templates#32]
Hey, we are using GH Action for DEV Integration and few others too.

But, DEV one seems failing since last 4 days. 

Here is the trace from GH Action run.

```
Run dev_orbit --check-comments
  dev_orbit --check-comments
  shell: /usr/bin/bash -e {0}
  env:
    ......ENV_VARS

/opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/lib/dev_orbit/dev.rb:86:in `get_articles':
undefined method `empty?' for #<Net::HTTPForbidden 403 Forbidden Bots readbody=true> (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/lib/dev_orbit/dev.rb:20:in `process_comments'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/lib/dev_orbit/client.rb:54:in `comments'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/scripts/check_comments.rb:13:in `render'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/dev_orbit-0.5.1/bin/dev_orbit:41:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/dev_orbit:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/bin/dev_orbit:23:in `<main>'

Checking for new DEV comments within the past day and posting them to your Orbit workspace...

Error: Process completed with exit code 1.

```

Appreciate your time looking into this. Thank You!

**Comment by KRRISH96** [comment]
Looks like its fixed!
